#!/usr/bin/env python3
"""Simulated OrcaSlicer harness for the Tetolator plugin.

Mimics the real `orca` bindings (verified against OrcaSlicer 2.4.2 source:
PythonPluginBridge.cpp / SlicingPipelinePluginCapability.cpp) so the actual
plugin file can be imported, its capability registered, and its `execute()`
path run end-to-end against a real Tetolator instance -- without the GUI.

Usage:
    python3 plugins/orcaslicer/tests/test_plugin_live.py <base_url>
"""

import json
import os
import sys
import tempfile
import types
import urllib.request
from pathlib import Path

BASE_URL = sys.argv[1] if len(sys.argv) > 1 else "http://127.0.0.1:5000"


# ---------------------------------------------------------------------------
# Minimal, faithful stub of the `orca` embedded module
# ---------------------------------------------------------------------------

class _PluginResult:
    Success = "Success"
    Skipped = "Skipped"
    RecoverableError = "RecoverableError"
    FatalError = "FatalError"


class _ExecutionResult:
    def __init__(self, status=None, message="", data=""):
        self.status = status
        self.message = message
        self.data = data

    @staticmethod
    def success(message="", data=""):
        return _ExecutionResult(_PluginResult.Success, message, data)

    @staticmethod
    def skipped(message=""):
        return _ExecutionResult(_PluginResult.Skipped, message)

    @staticmethod
    def failure(status, message, data=""):
        return _ExecutionResult(status, message, data)


class _Step:
    psGCodePostProcess = "psGCodePostProcess"
    posSlice = "posSlice"


class _SlicingPipelineCapabilityBase:
    def get_name(self):
        raise NotImplementedError


class _Ctx:
    def __init__(self, gcode_path, output_name):
        self.step = _Step.psGCodePostProcess
        self.gcode_path = gcode_path
        self.output_name = output_name
        self.host = "File"
        self._config = {}

    def config_value(self, key):
        return self._config.get(key)


class _PackageBase:
    pass


_registered = []


def _plugin(cls):
    return cls


def _register_capability(cls):
    _registered.append(cls)


_orca = types.ModuleType("orca")
_orca.PluginResult = _PluginResult
_orca.ExecutionResult = _ExecutionResult
_orca.base = _PackageBase
_orca.plugin = _plugin
_orca.register_capability = _register_capability
_slicing = types.ModuleType("orca.slicing")
_slicing.Step = _Step
_slicing.SlicingPipelineCapabilityBase = _SlicingPipelineCapabilityBase
_orca.slicing = _slicing

sys.modules["orca"] = _orca
sys.modules["orca.slicing"] = _slicing

# ---------------------------------------------------------------------------
# Import the real plugin now that `orca` is stubbed
# ---------------------------------------------------------------------------

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

# Isolate the duplicate-guard state file so tests don't touch the repo.
_STATE_DIR = tempfile.mkdtemp(prefix="tetolator_state_")
os.environ["TETOLATOR_PLUGIN_STATE_DIR"] = _STATE_DIR

import tetolator  # noqa: E402

# The host instantiates the package class and calls register_capabilities().
tetolator.TetolatorPackage().register_capabilities()
assert _registered == [tetolator.TetolatorLogger], "capability was not registered"
print("plugin imported and capability registered OK")

# ---------------------------------------------------------------------------
# Run execute() the way OrcaSlicer would
# ---------------------------------------------------------------------------

GCODE = """; generated by OrcaSlicer 2.4.2
; filament_type = PLA
; filament_settings_id = "Sunlu PLA+ @Bambu Lab P1P 0.4 nozzle"
; total filament used [mm3] = 2430.26
; total filament used [g] = 19.44
; estimated printing time (normal mode) = 2h 12m 33s
; estimated printing time (fast mode) = 1h 59m 1s
"""

capability = tetolator.TetolatorLogger()
capability._config = {
    "base_url": BASE_URL,
    "default_client_id": "1",
}
capability.get_config = lambda: json.dumps(capability._config)

plugin_dir = tempfile.mkdtemp(prefix="tetolator_plugin_test_")

with tempfile.NamedTemporaryFile(
    "w", suffix=".gcode", dir=plugin_dir, delete=False
) as handle:
    handle.write(GCODE)
    gcode_path = handle.name

ctx = _Ctx(gcode_path=gcode_path, output_name="benchy_0.2mm_PLA.gcode")

# pre-flight: no print with this signature should exist yet
result = capability.execute(ctx)
print("first execute ->", result.status, "|", result.message)
assert result.status == _PluginResult.Success, result.message

# verify it landed in Tetolator
with urllib.request.urlopen(BASE_URL + "/api/prints") as resp:
    prints = json.load(resp)
newest = prints[0]
assert newest["model_name"] == "benchy_0.2mm_PLA", newest
print("record created in Tetolator: id=%s total=%s filament=%s" % (
    newest["id"], newest["total_cost"], newest["filament_name"]))

# second execute of the same export must be skipped by the duplicate guard
result2 = capability.execute(ctx)
print("second execute ->", result2.status, "|", result2.message)
assert "already logged" in result2.message, result2.message

# a different model must create a NEW record
gcode_path2 = gcode_path.replace(".gcode", "_v2.gcode")
Path(gcode_path2).write_text(GCODE, encoding="utf-8")
ctx2 = _Ctx(gcode_path=gcode_path2, output_name="vase.gcode")
result3 = capability.execute(ctx2)
print("third execute (new model) ->", result3.status, "|", result3.message)
assert "logged" in result3.message and "already" not in result3.message

# empty output_name is still handled (logs as "untitled")
ctx3 = _Ctx(gcode_path=gcode_path, output_name="")
result4 = capability.execute(ctx3)
print("empty output_name ->", result4.status, "|", result4.message)

# unreachable server -> RecoverableError, no crash
capability._config["base_url"] = "http://127.0.0.1:1"
ctx5 = _Ctx(gcode_path=gcode_path, output_name="server_down_test.gcode")
result5 = capability.execute(ctx5)
print("server down ->", result5.status, "|", result5.message)
assert result5.status == _PluginResult.RecoverableError

# ---------------------------------------------------------------------------
# Cleanup: remove only the records this harness created
# ---------------------------------------------------------------------------

with urllib.request.urlopen(BASE_URL + "/api/prints") as resp:
    prints = json.load(resp)
mine = [
    p for p in prints
    if p["notes"] == "Auto-logged by OrcaSlicer plugin"
    and p["model_name"] in ("benchy_0.2mm_PLA", "vase", "untitled")
]
for p in mine:
    req = urllib.request.Request(f"{BASE_URL}/api/prints/{p['id']}", method="DELETE")
    urllib.request.urlopen(req, timeout=5).read()
print(f"cleaned up {len(mine)} test record(s): {[p['model_name'] for p in mine]}")

print("\nLIVE PLUGIN HARNESS PASSED")
