#!/usr/bin/env python3
"""Standalone unit tests for the Tetolator OrcaSlicer plugin helpers.

Runs without OrcaSlicer: `tetolator.py` imports `orca` optionally, so all
parsing/matching functions are testable here.

Usage:
    python3 plugins/orcaslicer/tests/test_parser.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import tetolator as t  # noqa: E402

SAMPLE_GCODE = """; generated by OrcaSlicer 2.4.2
; printer model = Bambu Lab P1S
; filament_type = PLA
; filament_settings_id = "Sunlu PLA+ @Bambu Lab P1P 0.4 nozzle"
; total filament used [mm3] = 2430.26
; total filament used [g] = 19.44
; total filament cost = 0.49
; estimated printing time (normal mode) = 2h 12m 33s
; estimated printing time (fast mode) = 1h 59m 1s
"""

def check(name, cond):
    if not cond:
        print(f"FAIL: {name}")
        sys.exit(1)
    print(f"ok:   {name}")

# --- parse_gcode_stats ---------------------------------------------------
stats = t.parse_gcode_stats(SAMPLE_GCODE)
check("weight parsed", stats["weight_used_g"] == 19.44)
check("hours parsed", stats["hours"] == 2)
check("minutes parsed (seconds 33 >= 30 rounds to 2:13)", stats["minutes"] == 13)
check("preset parsed", stats["filament_preset"] == "Sunlu PLA+ @Bambu Lab P1P 0.4 nozzle")
check("type parsed", stats["filament_type"] == "PLA")

# sub-hour time
sub_hour = t.parse_gcode_stats("; estimated printing time (normal mode) = 47m 12s\n")
check("sub-hour time", (sub_hour["hours"], sub_hour["minutes"]) == (0, 47))

# missing weight -> sum of per-filament lines
no_total = t.parse_gcode_stats(
    "; filament used [g] = 10.0\n; filament used [g] = 5.25\n"
)
check("missing total weight summed", abs(no_total["weight_used_g"] - 15.25) < 1e-9)

# empty / missing everything
empty = t.parse_gcode_stats("G1 X0 Y0\n")
check("empty -> zeroed", empty == {
    "weight_used_g": None, "hours": 0, "minutes": 0,
    "filament_preset": None, "filament_type": None,
})

# --- model_name_from_output ----------------------------------------------
check("output name stripped", t.model_name_from_output("benchy_0.2mm_PLA.gcode") == "benchy_0.2mm_PLA")
check("output with path", t.model_name_from_output("/tmp/out/foo.gcode") == "foo")
check("no extension", t.model_name_from_output("bar") == "bar")
check("empty output", t.model_name_from_output("") == "untitled")

# --- match_filament ------------------------------------------------------
filaments = [
    {"id": 1, "name": "Sunlu PLA+ Red", "brand": "Sunlu", "material": "PLA"},
    {"id": 2, "name": "eSun PETG Black", "brand": "eSun", "material": "PETG"},
]
check("exact preset match", t.match_filament("Sunlu PLA+ Red", "PLA", filaments) == 1)
check("substring match", t.match_filament("Sunlu PLA+ @Bambu Lab P1P 0.4 nozzle", "PLA", filaments) == 1)
check("material-only match", t.match_filament(None, "PETG", filaments) == 2)
check("no match -> None", t.match_filament("Something Else", "ABS", filaments) is None)
check("no filaments -> None", t.match_filament("x", "PLA", []) is None)

# --- payload + duplicate key ---------------------------------------------
config = {"base_url": "http://127.0.0.1:5000", "default_client_id": "3"}
payload = t.build_payload(stats, "benchy", config, filament_id=2)
check("payload model", payload["model_name"] == "benchy")
check("payload client", payload["client_id"] == "3")
check("payload filament", payload["filament_id"] == "2")
check("payload weight", payload["weight_used_g"] == 19.44)
check("payload time", (payload["hours"], payload["minutes"]) == (2, 13))
check("payload date format", len(payload["print_date"]) == 10)

k1 = t.compute_key("a", "2026-08-10", 1.0)
k2 = t.compute_key("a", "2026-08-10", 1.0)
k3 = t.compute_key("a", "2026-08-10", 1.5)
check("key stable", k1 == k2)
check("key differs on weight", k1 != k3)

# --- state file round-trip -----------------------------------------------
import tempfile
with tempfile.TemporaryDirectory() as tmp:
    t.save_state(tmp, {"abc": {"output_name": "x"}})
    check("state round-trip", t.load_state(tmp) == {"abc": {"output_name": "x"}})
check("missing state -> empty", t.load_state("/nonexistent") == {})

print("\nAll plugin helper tests passed.")
